extensions:
    pim-mass-product-edit-configure-add-to-existing-product-model-family:
        module: pim/form/common/creation/family
        parent: pim-mass-product-edit-configure-add-to-existing-product-model
        targetZone: fields
        position: 20
        config:
            identifier: family
            required: true
            fieldLabel: pim_enrich.entity.product.meta.family.title
            loadUrl: pim_enrich_family_index_get_variants

    pim-mass-product-edit-configure-add-to-existing-product-model-variant:
        module: pim/product-model/form/creation/variant
        parent: pim-mass-product-edit-configure-add-to-existing-product-model
        targetZone: fields
        position: 30
        config:
            fieldName: family_variant
            label: pim_enrich.form.product_model.family_variant
            required: true
            loadUrl: pim_datagrid_load

    pim-mass-product-edit-configure-add-to-existing-product-model-product-model:
        module: pim/product-model/form/product-model
        parent: pim-mass-product-edit-configure-add-to-existing-product-model
        targetZone: fields
        position: 40
        config:
            fieldName: product_model
            label: pim_enrich.form.product_model.product_model
            required: true
            loadUrl: pim_enrich_product_model_family_variant_leaf
